capitalise/app/urls.py
from django.urls import path
from app.views import *

urlpatterns = [
    path('usuario', usuario, name='usuario'),
]

capitalise/capitalise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('autenticacao.urls')),
    path('app', include('app.urls')),
    path('admin/', admin.site.urls)
]

capitalise/autenticacao/forms.py
from django import forms

class LoginForms(forms.Form):
    usuario=forms.CharField(
        label='Usuário',        
        required=True,
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Email',
                'icon': 'ph-user-circle'
            }
        )
    )
    senha=forms.CharField(
        label='Senha',        
        required=True,
        max_length=70,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '•••••••••••',
                'icon': 'ph-lock'
            }
        )
    )

class CadastroForms(forms.Form):
    email=forms.CharField(
        label='Email',        
        required=True,
        max_length=100,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Email',
                'icon': 'ph-user-circle'
            }
        )
    )
    nome=forms.CharField(
        label='Nome',        
        required=True,
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Nome',
                'icon': 'ph-user-circle'
            }
        )
    )
    telefone=forms.CharField(
        label='Telefone',        
        required=True,
        max_length=100,
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Telefone',
                'icon': 'ph-user-circle'
            }
        )
    )
    cpf=forms.CharField(
        label='Cpf',        
        required=True,
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Cpf',
                'icon': 'ph-user-circle'
            }
        )
    )
    senha=forms.CharField(
        label='Senha',        
        required=True,
        max_length=70,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '•••••••••••',
                'icon': 'ph-lock'
            }
        )
    )

capitalise/templates/app/cadastro/criar_carteira.html
<!-- criar_carteira.html -->

{% extends 'base.html' %}

{% block content %}
    <h1>Criar Carteira</h1>

    <form method="POST" action="{% url 'criar_carteira' %}">
        {% csrf_token %}
        <div>
            <label for="valor_aplicado">Valor Aplicado:</label>
            <input type="number" name="valor_aplicado" id="valor_aplicado">
        </div>
        <div>
            <label for="saldo_bruto">Saldo Bruto:</label>
            <input type="number" name="saldo_bruto" id="saldo_bruto">
        </div>
        <div>
            <label for="id_usuario">ID do Usuário:</label>
            <input type="number" name="id_usuario" id="id_usuario">
        </div>
        <button type="submit">Criar</button>
    </form>
{% endblock %}

capitalise/templates/app/cadastro/usuario.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Gerenciador de Investimentos</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Capitalise</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'criar_carteira' %}">Criar Carteira</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'adicionar_ativo' %}">Adicionar Ativo</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'visualizar_carteira' %}">Visualizar Carteira</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="teste" id="js-tab1" role="tabpanel">
    <form class="default" action="{% url 'usuario' %}" method="POST" novalidate>																				
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <p>Oi</p>
        <div class="mb-3">
            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
            {{ field }}
            {% if field.errors %}
                {% for error in field.errors %}
                <div class="invalid-feedback">{{ error }}</div>
                {% endfor %}
            {% else %}
                <div class="invalid-feedback">Campo obrigatório</div>
            {% endif %}
        </div>
        {% endfor %}
    </form>
</div>

  <div class="container mt-4">
    {% block content %}
    {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>